services:
  - type: web
    name: ai-course-builder
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: GEMINI_API_KEY
        sync: false
      - key: YT_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        # Set to your deployed URL(s), comma-separated. Example updated after first deploy.
        value: ""
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
